name: Get latest toolbox-server

on:
  push:
    branches:
      - main

jobs:
  get-latest-toolbox-server:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          mkdir -p $HOME/bin
          Invoke-WebRequest -Uri "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe" -OutFile "$HOME/bin/jq.exe"

      - name: Get latest release
        id: get-release
        run: |
          $url = "https://api.github.com/repos/ge-fei-fan/toolbox-server/releases/latest"
          $response = Invoke-WebRequest -Uri $url | ConvertFrom-Json
          $tag_name = $response.tag_name
          $asset_url = $response.assets | Where-Object { $_.name -like "*.exe" } | Select-Object -ExpandProperty browser_download_url
          echo "::set-output name=tag_name::$tag_name"
          echo "::set-output name=asset_url::$asset_url"

      - name: Download latest release
        run: |
          $asset_url = "${{ steps.get-release.outputs.asset_url }}"
          Invoke-WebRequest -Uri $asset_url -OutFile "toolbox-server.exe"
