name: Get Latest Toolbox Server

on:
  push:
    branches:
      - main

jobs:
  get_latest_toolbox_server:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @actions/github

      - name: Get latest release
        id: get_release
        run: |
          const { Octokit } = require("@octokit/core");
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

          const { data: releases } = await octokit.request('GET /repos/{owner}/{repo}/releases', {
            owner: 'ge-fei-fan',
            repo: 'toolbox-server'
          });
          const latestRelease = releases[0];
          const asset = latestRelease.assets.find(asset => asset.name === 'toolbox-server.exe');
          console.log(asset.browser_download_url);

      - name: Print latest release link
        run: echo "Latest toolbox-server.exe link:${{ steps.get_release.outputs.result }}"
